[2025-01-03T12:35:43.008+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-03T12:35:43.017+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.replicate manual__2025-01-03T12:35:41.705801+00:00 [queued]>
[2025-01-03T12:35:43.021+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.replicate manual__2025-01-03T12:35:41.705801+00:00 [queued]>
[2025-01-03T12:35:43.021+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-01-03T12:35:43.027+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): replicate> on 2025-01-03 12:35:41.705801+00:00
[2025-01-03T12:35:43.030+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-03T12:35:43.031+0000] {standard_task_runner.py:72} INFO - Started process 154 to run task
[2025-01-03T12:35:43.032+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl', 'replicate', 'manual__2025-01-03T12:35:41.705801+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpb7aeo6dj']
[2025-01-03T12:35:43.033+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask replicate
[2025-01-03T12:35:43.057+0000] {task_command.py:467} INFO - Running <TaskInstance: etl.replicate manual__2025-01-03T12:35:41.705801+00:00 [running]> on host f6c52e409999
[2025-01-03T12:35:43.095+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='replicate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T12:35:41.705801+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-03T12:35:41.705801+00:00'
[2025-01-03T12:35:43.096+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-03T12:35:43.099+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-03T12:35:43.100+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-01-03T12:35:43.105+0000] {logging_mixin.py:190} INFO - Table users has 0 rows
[2025-01-03T12:35:43.105+0000] {logging_mixin.py:190} INFO - Table orders has 0 rows
[2025-01-03T12:35:43.105+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-03T12:35:43.111+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-03T12:35:43.111+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl, task_id=replicate, run_id=manual__2025-01-03T12:35:41.705801+00:00, execution_date=20250103T123541, start_date=20250103T123543, end_date=20250103T123543
[2025-01-03T12:35:43.132+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-03T12:35:43.141+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-03T12:35:43.141+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
