[2025-01-03T13:23:06.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-03T13:23:06.038+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.replicate manual__2025-01-03T12:35:41.705801+00:00 [queued]>
[2025-01-03T13:23:06.042+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.replicate manual__2025-01-03T12:35:41.705801+00:00 [queued]>
[2025-01-03T13:23:06.042+0000] {taskinstance.py:2865} INFO - Starting attempt 8 of 8
[2025-01-03T13:23:06.048+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): replicate> on 2025-01-03 12:35:41.705801+00:00
[2025-01-03T13:23:06.051+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=392) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-03T13:23:06.053+0000] {standard_task_runner.py:72} INFO - Started process 393 to run task
[2025-01-03T13:23:06.053+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl', 'replicate', 'manual__2025-01-03T12:35:41.705801+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpx56b1tib']
[2025-01-03T13:23:06.054+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask replicate
[2025-01-03T13:23:06.087+0000] {task_command.py:467} INFO - Running <TaskInstance: etl.replicate manual__2025-01-03T12:35:41.705801+00:00 [running]> on host f6c52e409999
[2025-01-03T13:23:06.132+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='replicate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T12:35:41.705801+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-03T12:35:41.705801+00:00'
[2025-01-03T13:23:06.133+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-03T13:23:06.608+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-03T13:23:06.609+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-01-03T13:23:06.622+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-01-03T13:24:06.639+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-01-03T13:24:06.643+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-03T13:24:06.647+0000] {process_utils.py:132} INFO - Sending 15 to group 393. PIDs of all processes in the group: [393]
[2025-01-03T13:24:06.647+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 393
[2025-01-03T13:24:06.649+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-03T13:24:06.652+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-03T13:24:06.681+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=393, status='terminated', exitcode=2, started='13:23:05') (393) terminated with exit code 2
